# Generated by Django 5.2 on 2025-04-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tokens",
            field=models.IntegerField(default=0),
        ),
    ]
