# Generated by Django 5.2 on 2025-04-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="model_file",
            field=models.FileField(upload_to="assets/"),
        ),
    ]
