# Generated by Django 5.2 on 2025-04-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makers", "0002_alter_asset_model_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="complexity",
            field=models.TextField(default="medium"),
        ),
        migrations.AddField(
            model_name="asset",
            name="optimize_printing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="asset",
            name="style",
            field=models.TextField(default="realistic"),
        ),
    ]
